# Specify the logs bucket to store build logs
logsBucket: gs://cloud-build--pvt-logs

steps:
  # Step 1: Debug Step - List files in the current build context
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Listing files in the current build context:"
        ls -la

  # Step 2: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/project-24-uad/my-app-repo/nginx-image:latest', '.']

  # Step 3: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/project-24-uad/my-app-repo/nginx-image:latest']

  # Step 4: Deploy the application to GKE
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment/my-app'
      - 'my-app=us-central1-docker.pkg.dev/project-24-uad/my-app-repo/nginx-image:latest'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-central1-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=gke-1'

# Define substitutions (optional but helps with versioning)
substitutions:
  _DEPLOYMENT_NAME: 'my-app'
  _IMAGE: 'us-central1-docker.pkg.dev/project-24-uad/my-app-repo/nginx-image:latest'

# Specify images to build
images:
  - 'us-central1-docker.pkg.dev/project-24-uad/my-app-repo/nginx-image:latest'

# Specify the worker pool configuration
options:
  pool:
    name: 'projects/project-24-uad/locations/us-central1/workerPools/private-pool-3'
