# Specify the logs bucket to store build logs
logsBucket: gs://cloud-build--pvt-logs

steps:
  # Step 1: Debug Step - List files in the current build context
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Listing files in the current build context:"
        ls -la

  # Step 2: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/project-24-uad/my-app-repo/nginx-image:latest', '.']

  # Step 3: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/project-24-uad/my-app-repo/nginx-image:latest']

  # Step 4: Apply Deployment if it doesn't exist
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - '-'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-central1-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=gke-2'
    stdin:
      | # YAML for deployment definition
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: my-app
        labels:
          app: my-app
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: my-app
        template:
          metadata:
            labels:
              app: my-app
          spec:
            containers:
            - name: my-app
              image: us-central1-docker.pkg.dev/project-24-uad/my-app-repo/nginx-image:latest

  # Step 5: Update the deployment image if deployment already exists
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment/my-app'
      - 'my-app=us-central1-docker.pkg.dev/project-24-uad/my-app-repo/nginx-image:latest'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-central1-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=gke-2'

# Define substitutions (optional but helps with versioning)
substitutions:
  _DEPLOYMENT_NAME: 'my-app'
  _IMAGE: 'us-central1-docker.pkg.dev/project-24-uad/my-app-repo/nginx-image:latest'

# Specify images to build
images:
  - 'us-central1-docker.pkg.dev/project-24-uad/my-app-repo/nginx-image:latest'

# Specify the worker pool configuration
options:
  pool:
    name: 'projects/project-24-uad/locations/us-central1/workerPools/private-pool-2'